version: '3'

services:
  database:
    container_name: zyn
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=zyn
      - POSTGRES_PASSWORD=zyn
    volumes:
      - /data/postgres
    ports:
      - "5300:5432"